version: "3"
services:
  python:
    container_name: python
    restart: unless-stopped
    stdin_open: true
    ports:
      - 8000:8000
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./db.sqlite3:/db.sqlite3
  celery-beat:
    network_mode: "service:redis"
    build: .
    container_name: 'celery-beat'
    command: celery -A notificationservice beat -l info
  celery-worker:
    network_mode: "service:redis"
    build: .
    container_name: 'celery-worker'
    command: celery -A notificationservice worker -l info
    volumes:
      - ./db.sqlite3:/db.sqlite3
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - 6379:6379