# Generated by Django 4.0.6 on 2022-07-31 09:03

from django.db import migrations, models
import notificationservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=3, validators=[notificationservice.models.code_validator]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, validators=[notificationservice.models.phone_validator]),
        ),
    ]
