# Generated by Django 4.0.6 on 2022-08-01 13:51

from django.db import migrations, models
import notificationservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationservice', '0002_alter_client_code_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='code',
            field=models.CharField(max_length=3, validators=[notificationservice.models.code_validator]),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
